In [1]:
# Comando para dicir cual es la carpeta que estas trabajando
%pwd

'/Users/rodrigoalvarez/Documents/Master/02_HerramientasAnalisis/PEC1/02_La libreria Numpy'

In [2]:
a = [1, 2, 3, 4]

In [3]:
a * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
b = []
for i in a:
    b.append(i*3)
b

[3, 6, 9, 12]

In [5]:
import random

# List Comprehension

In [6]:
a

[1, 2, 3, 4]

In [7]:
# Creando una lista a partir de otra
[n for n in a]

[1, 2, 3, 4]

In [8]:
[n + 1 for n in a]

[2, 3, 4, 5]

In [9]:
[n * 3 for n in a]

[3, 6, 9, 12]

In [10]:
a = [2, 7, 5, 4, 8, 2, 1, 9]

In [12]:
[n ** 2 for n in a if n > 5]

[49, 64, 81]

In [13]:
[n for n in a]

[2, 7, 5, 4, 8, 2, 1, 9]

In [14]:
[n if n >= 5 else 0 for n in a]

[0, 7, 5, 0, 8, 0, 0, 9]

In [15]:
help(range)

Help on class range in module builtins:

class range(object)
 |  range(stop) -> range object
 |  range(start, stop[, step]) -> range object
 |  
 |  Return an object that produces a sequence of integers from start (inclusive)
 |  to stop (exclusive) by step.  range(i, j) produces i, i+1, i+2, ..., j-1.
 |  start defaults to 0, and stop is omitted!  range(4) produces 0, 1, 2, 3.
 |  These are exactly the valid indices for a list of 4 elements.
 |  When step is given, it specifies the increment (or decrement).
 |  
 |  Methods defined here:
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(self, key, /)
 |      Return self[key].
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |

In [17]:
# convirte una range en una lista
list(range (4, 8))

[4, 5, 6, 7]

In [35]:
# generar una lista con 10 miliones
a = [random.randint(1, 9) for _ in range(10000000)]


In [40]:
len(a)

10000000

In [41]:
import numpy as np

In [42]:
an = np.array(a)

In [43]:
# dimensiones del array
an.shape

(10000000,)

In [44]:
an.size

10000000

In [1]:
c = np.random.randint(0, 10, size =(4, 3))
c

NameError: name 'np' is not defined

In [46]:
c.shape

(4, 3)

In [47]:
c.size

12

In [48]:
an

array([6, 6, 7, ..., 7, 3, 8])

In [49]:
an.shape

(10000000,)

In [50]:
import math

In [51]:
%%time
b = []
for n in a:
    b.append(math.log(n))

CPU times: user 1.74 s, sys: 142 ms, total: 1.88 s
Wall time: 1.89 s


In [52]:
%%time
b = [math.log(n) for n in a]

CPU times: user 1.47 s, sys: 138 ms, total: 1.61 s
Wall time: 1.7 s


In [53]:
%%time
np.log(an)

CPU times: user 109 ms, sys: 48.7 ms, total: 157 ms
Wall time: 223 ms


array([1.79175947, 1.79175947, 1.94591015, ..., 1.94591015, 1.09861229,
       2.07944154])

In [54]:
a = [1, 2, 3]
b = [5, 6, 7]

In [55]:
a + b

[1, 2, 3, 5, 6, 7]

In [56]:
an = np.array(a)
bn = np.array(b)

In [57]:
an + bn

array([ 6,  8, 10])

In [58]:
an + 1

array([2, 3, 4])

In [59]:
an * 3

array([3, 6, 9])

In [63]:
g = [8, 5, 7, 0, 7, 9, 8, 7, 4, 6]
h = [4, 4, 2, 0, 5, 1, 6, 6, 8, 4]
gn = np.array(g)
hn = np.array(g+h)

In [61]:
gn[-1]

6

In [65]:
j = np.random.randint(0, 10, size =(5, 10))
j

array([[4, 6, 5, 1, 7, 5, 0, 2, 7, 9],
       [1, 3, 1, 9, 1, 0, 4, 1, 5, 2],
       [8, 0, 7, 5, 5, 2, 6, 3, 1, 2],
       [9, 7, 0, 6, 4, 5, 2, 0, 1, 4],
       [3, 3, 6, 5, 0, 9, 2, 8, 1, 4]])

In [66]:
# Extraer elemento del array [linea, columna]
j[1,2]

1

In [68]:
# Extraer linea entera
j[1,:]

array([1, 3, 1, 9, 1, 0, 4, 1, 5, 2])

In [69]:
j[1]

array([1, 3, 1, 9, 1, 0, 4, 1, 5, 2])

In [71]:
# Extraer una columna del array
j[:,0]

array([4, 1, 8, 9, 3])

In [73]:
j[1,2:4]

array([1, 9])

In [74]:
k = np.arange(20)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
l = np.arange(20).reshape(4, 5)
l

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
l[1,1:3]

array([6, 7])